### ISSUE TITLE
Typed arrays literals (eg `Int[1,2,3]`)

### ISSUE THREAD

**Issue by FelipeLema** [tree-sitter/tree-sitter-julia#10]
I get a parsing error when feeding a [typed array literal](https://docs.julialang.org/en/v1/manual/arrays/#Typed-array-literals) to emacs-tree-sitter

If I input
```julia
Float64[1, 2]
```
I get
```
((source_file
  (subscript_expression
   (identifier)
   (ERROR
    (number))
   (number)))
 . 75)
```

**Comment by ChrHorn** [comment]
This seems to be fixed.
```
source_file [0, 0] - [1, 0]
  subscript_expression [0, 0] - [0, 13]
    identifier [0, 0] - [0, 7]
    integer_literal [0, 8] - [0, 9]
    integer_literal [0, 11] - [0, 12]
```

**Comment by FelipeLema** [comment]
oh, I hadn't noticed... that's great.

would maintainers be willing to add this experssion to the tests? the more the merrier, right?
