### ISSUE TITLE
it's impossible to highlight `Symbol` literals differently from variables

### ISSUE THREAD

**Issue by ExpandingMan** [tree-sitter/tree-sitter-julia#110]
I've been a bit frustrated because, no matter what I do, my `Symbol` always has the color of variables.  Apparently, this is because `Symbol` literals are ultimately marked as `@variable`, see [my question here](https://github.com/neovim/neovim/discussions/24451).

Personally I would be happy if `Symbol` literals were of the highlight group `@symbol` only (this already is the case for the preceeding `:`), but, at the very least, it seems that `Symbol` literals should have a more specific highlight group, as it seems that most users would want them to be a different color than variables.

**Comment by savq** [comment]
I opened a PR (in nvim-treesitter) to ensure `@symbol` is applied after `@variable`.

**Comment by ExpandingMan** [comment]
Great! Thanks for the fast response!
