### ISSUE TITLE
Incorrectly parsed tuple assignment in let statement

### ISSUE THREAD

**Issue by Joel-Dahne** [tree-sitter/tree-sitter-julia#119]
The statement
```julia
let (x, y) = (0, 1)
    y
end
```
is valid Julia code. However, tree-sitter doesn't like it. Using the Emacs `julia-ts-mode` with `treesit-explore-mode` I get the output
```
(source_file
 (ERROR let)
 (assignment
  (tuple_expression ( (identifier) , (identifier) ))
  (operator)
  (tuple_expression ( (integer_literal) , (integer_literal) )))
 \n (identifier) \n (identifier) \n)
```
Unfortunately I haven't been able to figure out how to determine the version of the grammar I have installed.

Note that
```julia
let x, y = (0, 1)
    y
end
```
is **not** valid Julia code. This is likely related to why the above doesn't work as expected.

**Comment by dhanak** [comment]
I just ran into the same issue :-(.
