### ISSUE TITLE
parse error when using `function () end` as an anonymous function

### ISSUE THREAD

**Issue by FelipeLema** [tree-sitter/tree-sitter-julia#12]
When I input the following
```julia
a = function3(function ()
    return 1
end)
```
I get
```
((source_file
  (assignment_expression
   (identifier)
   (call_expression
    (identifier)
    (argument_list
     (ERROR))))
  (return_statement
   (number))
  (identifier)
  (ERROR))
 . 154)
```
On the other hand, using the `->` notation, the code gets parsed OK, see below.
Input:
```julia
a = function3(()->begin
    return 1
end)
```
Parsed tree
```
((source_file
  (assignment_expression
   (identifier)
   (call_expression
    (identifier)
    (argument_list
     (function_expression
      (parameter_list)
      (compound_expression
       (return_statement
        (number))))))))
 . 186)
```

**Comment by maxbrunsfeld** [comment]
Hey, thank you for opening these issues. It may take a week or two for me to take a close look. For context, my estimate is that the grammar may be around 60% complete. The way that you've isolated these parse errors is super useful 👍 .

**Comment by FelipeLema** [comment]
it's most likely that I'll try to solve some of them  (including adding tests), but it will also take me a few weeks to do so.
