### ISSUE TITLE
Upstream queries

### ISSUE THREAD

**Issue by savq** [tree-sitter/tree-sitter-julia#133]
[Treesitter v0.21.0](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.21.0) made last-wins precedence the default, meaning tree-sitter queries now work in the same order as nvim ~/helix~ queries.

[nvim-treesitter also renamed some captures](https://github.com/nvim-treesitter/nvim-treesitter/pull/5895) to align with tree-sitter and helix. 

This means maintaining a common set of queries is much easier now, it would reduce some duplicated efforts between editors, and also make it easier to handle breaking changes downstream.

**Comment by clason** [comment]
Nit: Helix is still using the old first-wins precedence; efforts to change are underway but going (very) slowly.

**Comment by savq** [comment]
Someone had already opened a PR in helix to update the julia queries, including the precedence. See https://github.com/helix-editor/helix/pull/10031. I assume that'll get merged when helix switches. So it'll be easy for them to follow upstream too.

![oh-yeah-its-all-coming-together](https://github.com/tree-sitter/tree-sitter-julia/assets/30883030/d391287b-c2d1-4215-94c4-00a4a08b7351)
