### ISSUE TITLE
Easier/cleaner way to write tree-sitter grammar

### ISSUE THREAD

**Issue by mingodad** [tree-sitter/tree-sitter-julia#149]
Here https://mingodad.github.io/lua-wasm-playground/ there is an easier/cleaner way to write tree-sitter grammars like `Julia` (select `Tree-sitter-ebnf-generator-Julia` from `Examples` then click `Run` to see a full commented out `grammar.js` from the `EBNF` variant describng the grammar in `
Input Text (arg[1])`).

I hope it can be helpful !

**Comment by savq** [comment]
While the js grammars are overly verbose, the difficulty in developing the grammar is not in the syntax. This layer of indirection doesn't really solve anything, and it doesn't allow things like using JS function to "parameterize" rules (e.g. `integer_literal`).
