### ISSUE TITLE
Macrocall parsing rule allows newlines between arguments if they are stirngs

### ISSUE THREAD

**Issue by steffenhaug** [tree-sitter/tree-sitter-julia#150]
In reference to https://github.com/JuliaEditorSupport/zed-julia/issues/15#issuecomment-2329739530.

It appears that top-level macro calls allow newlines between arguments if the argument after the newline is a string.

It is my understanding that _only the `@doc` macro_ is handled as a special case in the parser to allow newlines between macro arguments, and that newlines are only allowed between the first and second argument. [The advanced usage section](https://docs.julialang.org/en/v1/manual/documentation/#Advanced-Usage) of the documentation manual is pretty clear about this.

<img width=500 src="https://github.com/user-attachments/assets/13457608-8db6-4688-8889-34bb442e66c3">

This makes it quite tricky to correctly find docstrings if there are macros used at the top level.

It seems quite strange to me that something like this can go unnoticed, given the prevalence of `@kwdef` in particular, yet I could find no issues mentioning this, closed or open. I appreciate that this kind of context-sensitivity might be really tricky to implement in tree-sitter.

For the record, it is possible to have any number of newline-separated arguments, not just newlines between the first and second argument.

<img width=500 src="https://github.com/user-attachments/assets/115649af-7fba-4dc0-9dae-af658078daa3">

But funnily enough, if the newline separates an argument that isn't a string literal, it is not parsed as part of the macro call, _even though it is_ in the special case of `@doc`:

<img width=500 src="https://github.com/user-attachments/assets/f3eec074-d9b5-4cc4-aa57-69b09fb2af89">

Is this behavior a conscious choice?

**Comment by savq** [comment]
Hi @steffenhaug, thanks for the report.

We don't handle `@doc` at all. This is probably a bug in the scanner with the way we parse the start of the string.

Please use the issue template next time.
