### ISSUE TITLE
Is "parametere" field in function_definition a typo?

### ISSUE THREAD

**Issue by Honeypot95** [tree-sitter/tree-sitter-julia#21]
Is this a typo? I was trying to construct some queries on a parameter list, and accidentally saw that it worked only when I typed "parametere", which seems like a typo, as "e" and "s" are very close.

https://github.com/tree-sitter/tree-sitter-julia/blob/0ba7a24b062b671263ae08e707e9e94383b25bb7/grammar.js#L144

**Comment by maxbrunsfeld** [comment]
Yes, that's a typo. 😁

**Comment by Honeypot95** [comment]
Alright, I will correct it, if nobody does it before.
