### ISSUE TITLE
Highlighting Number*variable

### ISSUE THREAD

**Issue by m-wells** [tree-sitter/tree-sitter-julia#25]
The following are currently highlighted differently
```julia
y = 3*x
y = 3x
```
such that `x` is no longer recognized as a variable.

**Comment by ChrHorn** [comment]
This seems to be an issue with the queries of your editor. Looks fine for me:
![image](https://user-images.githubusercontent.com/17070041/199980943-dbd1b6a9-595c-40e1-9495-999742736c3f.png)
