### ISSUE TITLE
triplequote / newline / Comment interaction

### ISSUE THREAD

**Issue by Jasha10** [tree-sitter/tree-sitter-julia#29]
Inconsistent parsing of @foo_str triplequote containing newline and followed by commment (see screenshot below):
![screenshot](https://user-images.githubusercontent.com/8935917/147999804-dacfa1dd-a973-497d-83f4-f7db5b3af237.jpeg)

Here is the text in the example:
```julia
foo"""bar
"""

baz()

# """"""

qux()

```

**Comment by maxbrunsfeld** [comment]
Thanks for the report.
