### ISSUE TITLE
Multiline comments are not supported

### ISSUE THREAD

**Issue by SimonMandlik** [tree-sitter/tree-sitter-julia#30]
Using treesitter highlighting:

<img width="82" alt="image" src="https://user-images.githubusercontent.com/16707112/148650343-13792bf1-c29e-4f51-bf4f-18e30e866be6.png">

**Comment by koalp** [comment]
It seems that it is an issue from nvim-treesitter and not from the parser.

I have been able to enable block comments highlighting. I’ve created a PR here to try to solve the issue : https://github.com/nvim-treesitter/nvim-treesitter/pull/2246

**Comment by clason** [comment]
That PR is now merged -- can you test again?

**Comment by SimonMandlik** [comment]
Looks good!
