### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by jussij** [tree-sitter/tree-sitter-julia#32]
In the latest release, in the scanner.c file there is this function:

```
    static void deserialize_stack(Stack *stack, const char *buffer, unsigned len) {
      if (len > 0) {
        memcpy(stack->arr, buffer, len);
        stack->len = len;
      } else {
        Delimiter *arr = malloc(TREE_SITTER_SERIALIZATION_BUFFER_SIZE);
        if (arr == NULL) exit(1);
        stack->arr = arr;
        stack->len = 0;
      }
    }
```
I think that code is missing a call to the free function and as such is leaking memory.

The code needs a call free as shown below:

```
    static void deserialize_stack(Stack *stack, const char *buffer, unsigned len) {
      if (len > 0) {
        memcpy(stack->arr, buffer, len);
        stack->len = len;
      } else {
        free(stack->arr); // ******* Need this line of code to fix memory leak ******* 
        Delimiter *arr = malloc(TREE_SITTER_SERIALIZATION_BUFFER_SIZE);
        if (arr == NULL) exit(1);
        stack->arr = arr;
        stack->len = 0;
      }
    }
```

**Comment by savq** [comment]
Yep. I can confirm there's a `free` missing there. Sorry.

Although now I wonder if there's even a need to call `malloc` again here. Resetting the length to zero should work fine if the stack keeps ownership of `arr` between calls to the scanner.

**Comment by maxbrunsfeld** [comment]
Yes, @savq can you try avoiding the extra `malloc`, and see if you can get that to work?

**Comment by savq** [comment]
Removing `malloc` works. In fact it allocates exactly the same amount of memory as placing the `free`, so I'd assume the compiler would optimize away the consecutive `free` and `malloc`.
