### ISSUE TITLE
Update the treesitter version to 0.20.0

### ISSUE THREAD

**Issue by VarLad** [tree-sitter/tree-sitter-julia#40]
I did commend on this in the 'project status' issue
Some new editors now work with tree-sitter 0.20.0 release and using this version of tree-sitter-julia there isn't feasible in my experience. I did try bumping the version in `Cargo.toml` to try with a an editor but that broke some stuff.
How much work would it take to port tree-sitter-julia to tree-sitter 0.20.0?

**Comment by clason** [comment]
You need to be much more specific; this parser works perfectly fine in Neovim, which uses the latest tree-sitter 0.20.6?

**Comment by VarLad** [comment]
@clason I'm trying to implement it for the Lapce editor, while using this parser and the highlight queries from nvim-treesitter repo. 
I had to bump the version for the Rust binding to 0.20 to make it compile. It does work but the behavior is that it treats function calls and a bunch of other stuff as a variable when highlighting which made me think if there was something wrong with just bumping the version of tree-sitter in Cargo.toml and using nvim queries
