### ISSUE TITLE
String and command suffixes

### ISSUE THREAD

**Issue by MichaelHatherly** [tree-sitter/tree-sitter-julia#7]
Related to #6:

- literal suffixes aren't supported for any of the literal syntaxes, i.e `` r"..."i `` for regex flags.
- triple-backtick command literals aren't implemented,
- triple-strings and triple-backticks don't currently support either prefixes or suffixes.

**Comment by gzagatti** [comment]
I am having a similar problem. 

I find that the lack of support for strings of the type

```jl
md"""
Hello world!
"""
```

Makes it very hard to read Pluto notebooks from the source file since they use the md prefix for text cells.

**Comment by savq** [comment]
The only remaining issue here are string suffixes, so I'll update the title of the issue.
