### ISSUE TITLE
`if` inside comprehension not captured

### ISSUE THREAD

**Issue by mroavi** [tree-sitter/tree-sitter-julia#94]
The `if` filter inside a [comprehension](https://docs.julialang.org/en/v1/manual/arrays/#man-comprehensions) is not captured. Would it be possible to support capturing and highlighting it?
```julia
[(i,j) for i=1:3 for j=1:i if i+j == 4]
```
![image](https://user-images.githubusercontent.com/19517248/213935164-206a6002-a140-45b8-8fec-6393c19ce693.png)

**Comment by savq** [comment]
This happens in Neovim, right? It'd only require a small change to the nvim queries. See https://github.com/nvim-treesitter/nvim-treesitter/pull/4204

**Comment by mroavi** [comment]
Yes, it occurs in Neovim. Thanks for the fix!
