### ISSUE TITLE
Subtype operator in parametric composite type definition not captured in Neovim 

### ISSUE THREAD

**Issue by mroavi** [tree-sitter/tree-sitter-julia#95]
The `<:` operator in the code below is not properly captured and highlighted in Neovim. I think this can also be solved with a query (in the future, should I open this kind of PRs in https://github.com/nvim-treesitter/nvim-treesitter instead?)

```julia
struct Point{T} <: Pointy{T}
  x::T
  y::T
end
```
![image](https://user-images.githubusercontent.com/19517248/214130410-f0e7f75d-bc80-4943-aa03-979a70cf97b4.png)

**Comment by fredrikekre** [comment]
Fixed:
```julia
struct A <: B
end
```
```
(struct_definition) ; [1:1 - 2:3]
 name: (identifier) ; [1:8 - 8]
 (type_clause) ; [1:10 - 13]
  (operator) ; [1:10 - 11]
  (identifier) ; [1:13 - 13]
```
