### ISSUE TITLE
Julia parser takes disproportionally long to compile on windows

### ISSUE THREAD

**Issue by henriqpsantos** [tree-sitter/tree-sitter-julia#97]
I'm using clang on Windows 10, other parsers are very fast to compile. This parser takes a very, very long time, and I can't be sure it's not stuck. I don't really know how I can provide any more information but I'm happy to provide what you need.

**Comment by savq** [comment]
Yep, the parser is just slow because the grammar has lots of conflicts.

Right now I'm more interested in making the resulting binary smaller (it's huge), but hopefully that will also reduce compilation time.

**Comment by RubixDev** [comment]
I noticed this when trying to compile to Wasm with emscripten `emcc`, my computer kills the process after some time because there is no RAM left.

**Comment by maxbrunsfeld** [comment]
I think this is fixed on the master branch. I'm going to close this out because the wasm compilation now takes 30 seconds. Still slow, but not unusable anymore.

Let me know if there are still problems compiling on windows.
